# 微服务端口
server:
  port: 7002

# 注册中心
eureka:
  instance:
    # eureka服务端的实例名称
    # hostname: localhost
    hostname: eureka7002.com # eureka服务端集群版写法
  client:
    # false 表示eureka自己不向注册中心注册自己
    register-with-eureka: false
    # false 表示自己端就是注册中心，我的职责是维护服务实例，并不需要去检索服务。fetch-registry（提取注册表）
    fetch-registry: false
    # 设置与 Eureka Server 交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
