# 微服务名称 和 数据源配置
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.15.37.148:3855/Cwz_Cloud?verifyServerCertificate=false&useSSL=false&characterEncoding=UTF-8
    username: root
    password: mysql294348

# 微服务端口
server:
  port: 8001

# mybatis
mybatis:
  type-aliases-package: com.cwz.springcloud.entities
  mapper-locations: classpath:mapper/*.xml

# 日志
logging:
  level:
    com:
      cwz:
        springcloud:
          dao: debug

# eureka client配置
eureka:
  client:
    # 表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 单机版
      # defaultZone: http://localhost:7001/eureka
      # eureka服务端集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  # 实例名也就是InstanceInfo类中的instanceId属性，它是区分同一服务中不同实例的唯一标识。 （修改actuator的主机名称）
  instance:
    instance-id: payment8001
    # 访问路径可以显示IP地址
    prefer-ip-address: true
#    # 表示eureka client发送心跳给表示eureka server端的频率
#    lease-renewal-interval-in-seconds: 1
#    # 表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将该服务移除
#    lease-expiration-duration-in-seconds: 2


