# 微服务端口
server:
  port: 7001

# 注册中心
eureka:
  instance:
    # eureka服务端的实例名称
    # hostname: localhost
    hostname: eureka7001.com # eureka服务端集群版写法
  client:
    # false 表示eureka自己不向注册中心注册自己
    register-with-eureka: false
    # false 表示自己端就是注册中心，我的职责是维护服务实例，并不需要去检索服务。fetch-registry（提取注册表）
    fetch-registry: false
    # 设置与 Eureka Server 交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/
#  # 开启(true)或关闭(false)自我保护机制
#  server:
#    enable-self-preservation: false
#    # eureka server清理无效节点的时间间隔，默认60000毫秒，即60秒（毫秒）
#    eviction-interval-timer-in-ms: 2000

