# 微服务端口
server:
  port: 800

# 微服务名称
spring:
  application:
    name: cloud-order-hystrix-service

# eureka client配置
eureka:
  client:
    # 表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka
      # eureka服务端集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: order-hystrirx-800
    # 访问路径可以显示IP地址
    prefer-ip-address: true
#eureka:
#  client:
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

## 设置feign客户端超时时间（OpenFeign默认支持ribbon）
#ribbon:
#  # 指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间（5秒）
#  ReadTimeout: 5000
#  # 指的是建立连接后从服务器读取到可用资源所用的时间（5秒）
#  ConnectTimeout: 5000
#logging:
#  level:
#   # feign日志以什么级别监控哪个接口
#   com.cwz.springcloud.service.PaymentFeignService: debug

# 开启hystrix
feign:
  hystrix:
    enabled: true
